### PR TITLE
CMO 2021 Announcement

### PR DESCRIPTION
**Pull request by joshukraine**
This PR will add a new blog post announcing CMO 2021. Also included will be minor fixes and dependency updates.

### CODE REVIEW

**Comment by speedy1812** [comment]
FWIW, the most current version of Node is now 14.15.5. Also, don't forget to update the `.travis.yml` file.

**Comment by joshukraine** [comment]
> FWIW, the most current version of Node is now 14.15.5. Also, don't forget to update the Ruby version in the `.travis.yml` file.

Good catch. Will fix!

**Review by speedy1812 — APPROVED** [review]
I thought the video looked a little crowded with the paragraph above it, but other than that, looks good!

**Comment by joshukraine** [comment]
> I thought the video looked a little crowded with the paragraph above it, but other than that, looks good!

Yeah, me too. Probably should tweak some CSS somewhere to fix that. Let me look...

**Comment by joshukraine** [comment]
@speedy1812 OK tweaked the video spacing. Also made it a bit wider (700px).

Screen Shot 2021-03-02 at 6 28 07 PM

**Pull request merged**
